name = "reward-tracker"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[[kv_namespaces]]
binding = "CACHE"
id = "b674965e3d5144cf8b32386bbc6f83cf"

[triggers]
crons = ["*/30 * * * *"]
